name = "Create Aeronautics - Skybound - Create Aeronautics & Create Addons with Quests (original)"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b08a7b0883b491c8defad2b3334ba0efa6c076b8c55dcfae15948cbcfff53111"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
