name = "Create Aeronautics - Skybound - Create Aeronautics & Create Addons with Quests (original)"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "393f4f84f0efb88525e65925a82a21ae797ed75716b37ad3ec98bd516808198d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
