name = "Create Aeronautics - Skybound - Create Aeronautics & Create Addons with Quests (original)"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4342b39aee978a89a9ae8ad5006669eb65b70e23ea798f2dbf77c6ad20e061cd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
