#Create Aeronautics Toolgun Client Settings
#Sat Jun 13 20:45:55 MDT 2026
autoWeldEnabled=false
bearingAxisMode=AUTO
bearingAxisVisualsEnabled=true
connectedSublevelProximity=0.5
connectionMode=FIXED
deleteRange=8
hudEnabled=true
magneticMarkersEnabled=true
nearbyQueryRange=0
offsetX=0
offsetY=0
offsetZ=0
panel=QUERY
previewEnabled=true
rangeDeleteEnabled=false
rotationDegrees=105
rotationStep=15
scalePercent=100
selectedFile=create_physical\:rud_mobile.nbt
snapMode=FACE_CENTER
translateStep=0.25
weldAdjustStep=0.25
weldSelectionMode=FACE_POINTS
